const Constants = {
    GET_USER_INFO :"GET_USER_INFO",
    GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS",
    GET_USER_ID_SUCCESS:"GET_USER_ID_SUCCESS",
    SELECTED_DATE:"SELECTED_DATE",
    SELECTED_TIME:"SELECTED_TIME",
    SELECTED_MESSAGE:"SELECTED_MESSAGE",
    GET_TASK_DATA:"GET_TASK_DATA",
    EDIT_DATA:"EDIT_DATA",
    CLEAR_USER_DATA:"CLEAR_USER_DATA",
    GET_TASK_DATA_SUCCESS: "GET_TASK_DATA_SUCCESS",
    SAVE_TASK_DATA_ERROR:"SAVE_TASK_DATA_ERROR",
    CLOSE_BANNER:"/CLOSE_BANNER"

}

export default Constants;